import { Inter } from "next/font/google";
import "./globals.css";
import { i18n } from "@/i18n.config";
import SideBar from "@/components/sidebar";
import cn from "@/lib/tailwindMerge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Atsmai",
   description: "Generated by create next app",
};

export async function generateStaticParams() {
   return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }) {
   return (
      <html
         dir={params.lang === "he" ? "rtl" : "ltr"}
         lang={params.lang}
         data-theme="dark"
      >
         <body className={cn(inter.className, "bg-base-100 min-h-screen ")}>
            <SideBar lang={params.lang}>
               <main className="p-5 h-screen">{children}</main>
            </SideBar>
         </body>
      </html>
   );
}
