import { Inter } from "next/font/google";
import "./globals.css";
import { i18n } from "@/i18n.config";
import SideBar from "@/components/navs/sidebar";
import cn from "@/lib/tailwindMerge";
import { getTheme } from "@/actions";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Atsmai",
   description: "Generated by create next app",
};

export async function generateStaticParams() {
   return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }) {
   const theme = (await getTheme()) || "dark";

   return (
      <html
         dir={params.lang === "he" ? "rtl" : "ltr"}
         lang={params.lang}
         data-theme={theme}
      >
         <body className={cn(inter.className, "bg-base-100 min-h-screen ")}>
            <SideBar lang={params.lang} sessionTheme={theme}>
               <main className="sm:p-5 h-screen">{children}</main>
            </SideBar>
         </body>
      </html>
   );
}
