import {
   ArrowPathIcon,
   ArrowsUpDownIcon,
   BriefcaseIcon,
   MagnifyingGlassIcon,
} from "@heroicons/react/24/outline";
import { getServerSession } from "next-auth";
import SignOutBtn from "./signOutBtn";
import SignInBtn from "./signInBtn";
import RegisterBtn from "./registerBtn";
import MenuLink from "./menuLink";

const SidebarContent = async ({ lang }) => {
   const session = await getServerSession();

   const user = session?.user || null;
   const avatar =
      user?.image ||
      "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png";

   const links = [
      {
         title: "Entries",
         href: "",
         icon: <ArrowsUpDownIcon className="h-5 w-5" />,
      },
      {
         title: "Recurring expenses",
         href: "recurring-expenses",
         icon: <ArrowPathIcon className="h-5 w-5" />,
      },
      {
         title: "Search Entries",
         href: "search",
         icon: <MagnifyingGlassIcon className="h-5 w-5" />,
      },
      {
         title: "Projects",
         href: "/",
         icon: <BriefcaseIcon className="h-5 w-5" />,
      },
   ];

   return (
      <div className="flex flex-col gap-3 p-4 w-80 min-h-full bg-base-200 text-base-content">
         {/* Sidebar content here */}
         {/* <Header lang={params.lang} /> */}

         <ul>
            {links.map((link) => (
               <MenuLink key={link.title} link={link} />
            ))}
         </ul>
         <ul className="mt-auto space-y-3 grid place-items-center ">
            <div className="divider w-full"></div>
            <li> {user?.name}</li>
            {session && (
               <li>
                  <div className="avatar">
                     <div className="h-20 rounded-full">
                        <img src={avatar} alt="Profile image" />
                     </div>
                  </div>
               </li>
            )}
            <li>
               {session ? (
                  <SignOutBtn />
               ) : (
                  <div className="flex gap-3">
                     <SignInBtn />
                     <RegisterBtn />
                  </div>
               )}
            </li>
            <li className="text-xs text-opacity-50 pt-5">
               Generated by Yoel Bar-Lev
            </li>
         </ul>
      </div>
   );
};

export default SidebarContent;
