import {
   ArrowPathIcon,
   ArrowsUpDownIcon,
   BriefcaseIcon,
   MagnifyingGlassIcon,
   InformationCircleIcon,
   EnvelopeIcon,
   HomeIcon,
} from "@heroicons/react/24/outline";
import { getServerSession } from "next-auth";
import SignOutBtn from "./signOutBtn";
import SignInBtn from "./signInBtn";
import RegisterBtn from "./registerBtn";
import MenuLink from "./menuLink";
import { format } from "date-fns";
import { getDictionary } from "@/lib/dictionary";
import Link from "next/link";

const currentDate = format(new Date(), "MM-yy");
const protectedLinks = [
   {
      title: "Entries",
      key: "entries",
      href: `?entriesType=incomes&month=${currentDate}`,
      icon: <ArrowsUpDownIcon className="h-5 w-5" />,
   },
   {
      title: "Recurring expenses",
      key: "recurringExpenses",
      href: "recurring-expenses",
      icon: <ArrowPathIcon className="h-5 w-5" />,
   },
   {
      title: "Search Entries",
      key: "searchEntries",
      href: "search?entriesType=incomes",
      icon: <MagnifyingGlassIcon className="h-5 w-5" />,
   },
   // {
   //    title: "Projects",
   //    href: "/",
   //    icon: <BriefcaseIcon className="h-5 w-5" />,
   // },
   {
      title: "About",
      key: "about",
      href: "/about",
      icon: <InformationCircleIcon className="h-5 w-5" />,
   },
   {
      title: "Contact",
      key: "contact",
      href: "/contact",
      icon: <EnvelopeIcon className="h-5 w-5" />,
   },
];

const publicLinks = [
   {
      title: "Welcome",
      key: "welcome",
      href: "/welcome",
      icon: <HomeIcon className="h-5 w-5" />,
   },
   {
      title: "About",
      key: "about",
      href: "/about",
      icon: <InformationCircleIcon className="h-5 w-5" />,
   },
   {
      title: "Contact",
      key: "contact",
      href: "/contact",
      icon: <EnvelopeIcon className="h-5 w-5" />,
   },
];

const SidebarContent = async ({ lang }) => {
   const { menuLinks, common } = await getDictionary(lang);
   const session = await getServerSession();

   const user = session?.user || null;
   const avatar =
      user?.image ||
      "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png";

   return (
      <div className="flex flex-col gap-3 p-4 w-80 min-h-full bg-base-200 text-base-content">
         {/* Sidebar content here */}
         {/* <Header lang={params.lang} /> */}
         <ul>
            {session
               ? protectedLinks.map((link) => (
                    <MenuLink key={link.title} link={link} text={menuLinks} />
                 ))
               : publicLinks.map((link) => (
                    <MenuLink key={link.title} link={link} text={menuLinks} />
                 ))}
         </ul>
         <ul className="mt-auto space-y-3 grid place-items-center ">
            <div className="divider w-full"></div>
            <li> {user?.name}</li>
            {session && (
               <li>
                  <Link href={`/${lang}/profile`} className="avatar ">
                     <div className="h-20 rounded-full hover:ring-4 hover:ring-primary hover:scale-110  active:ring-4 active:ring-primary active:scale-110 transition-all duration-150">
                        <img src={avatar} alt="Profile image" />
                     </div>
                  </Link>
               </li>
            )}
            <li>
               {session ? (
                  <SignOutBtn text={common} />
               ) : (
                  <div className="flex gap-3">
                     <SignInBtn text={common} />
                     <RegisterBtn text={common} />
                  </div>
               )}
            </li>
            <li className="text-xs text-opacity-50 pt-5">
               Generated by Yoel Bar-Lev
            </li>
         </ul>
      </div>
   );
};

export default SidebarContent;
