import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/contexts/providers";
import { ThemeModeScript } from "flowbite-react";
import cn from "./lib/tailwindMerge";
import SideBarComponent from "./components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Atsmai",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html dir="rtl" lang="he">
         <head>{/* <ThemeModeScript /> */}</head>
         <body
            className={cn(
               inter.className,
               " min-h-screen dark:bg-gray-900 dark:text-white flex"
            )}
         >
            <Providers>
               <SideBarComponent />
               <main className="flex-1 p-5 max-w-md mx-auto">{children}</main>
            </Providers>
         </body>
      </html>
   );
}
