import { addDays, subMonths } from "date-fns";

export function generateIncomes(userId) {
   return [
      {
         userId: userId,
         amount: 500,
         category: "Sales Revenue",
         date: subMonths(new Date(1), 2),
      },
      {
         userId: userId,
         amount: 300,
         category: "Consulting Fees",
         date: subMonths(new Date(1), 2),
      },
      {
         userId: userId,
         amount: 700,
         category: "Product Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "Service Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 400,
         category: "Investment Income",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "Royalties",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Advertising Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 500,
         category: "Sales Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 300,
         category: "Consulting Fees",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 700,
         category: "Product Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "Service Revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 400,
         category: "Investment Income",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "Royalties",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Advertising Revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 500,
         category: "Sales Revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 300,
         category: "Consulting Fees",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 700,
         category: "Product Revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2500,
         category: "Service Revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 400,
         category: "Investment Income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 600,
         category: "Royalties",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Advertising Revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 4500,
         category: "Grants",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 5500,
         category: "Interest Income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 200,
         category: "Rental Income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 7500,
         category: "Contractual Income",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3200,
         category: "Subscription Revenue",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 4800,
         category: "Donations",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3800,
         category: "Licensing Fees",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 4200,
         category: "Sponsorships",
         date: new Date(),
      },
   ];
}

export function generateExpenses(userId) {
   return [
      {
         userId: userId,
         amount: 2500,
         category: "Office Supplies",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Marketing",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Travel Expenses",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 800,
         category: "Utilities",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1750,
         category: "Business Meals",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 200,
         category: "Equipment",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 900,
         category: "Advertising",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3000,
         category: "Insurance",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1500,
         category: "Software",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "Training",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Consulting",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "Office Supplies",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Marketing",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Travel Expenses",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 800,
         category: "Utilities",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1750,
         category: "Business Meals",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2000,
         category: "Equipment",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 900,
         category: "Advertising",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3000,
         category: "Insurance",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1500,
         category: "Software",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 600,
         category: "Training",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Consulting",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2500,
         category: "Office Supplies",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Marketing",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3500,
         category: "Travel Expenses",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 800,
         category: "Utilities",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1750,
         category: "Business Meals",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 2000,
         category: "Equipment",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 900,
         category: "Advertising",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3000,
         category: "Insurance",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1500,
         category: "Software",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 600,
         category: "Training",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1200,
         category: "Consulting",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1800,
         category: "Rent",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 500,
         category: "Maintenance",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 700,
         category: "Legal Fees",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 400,
         category: "Transportation",
         date: new Date(),
      },
   ];
}

export function generateRecurringExpenses(userId) {
   const today = new Date();
   return [
      {
         userId,
         title: "Office Supplies",
         amount: 120,
         category: "Office Expenses",
         startDate: addDays(today, 1),
         nextOccurrence: addDays(today, 1),
      },
      {
         userId,
         title: "Internet Subscription",
         amount: 80,
         category: "Utilities",
         startDate: addDays(today, 2),
         nextOccurrence: addDays(today, 2),
      },
      {
         userId,
         title: "Marketing Fees",
         amount: 350,
         category: "Marketing",
         startDate: addDays(today, 3),
         nextOccurrence: addDays(today, 3),
      },
      {
         userId,
         title: "Rent",
         amount: 1500,
         category: "Office Expenses",
         startDate: addDays(today, 4),
         nextOccurrence: addDays(today, 4),
      },
      {
         userId,
         title: "Software Subscription",
         amount: 200,
         category: "Software",
         startDate: addDays(today, 5),
         nextOccurrence: addDays(today, 5),
      },
      {
         userId,
         title: "Maintenance Services",
         amount: 300,
         category: "Facilities",
         startDate: addDays(today, 6),
         nextOccurrence: addDays(today, 6),
      },
      {
         userId,
         title: "Employee Salaries",
         amount: 5000,
         category: "Payroll",
         startDate: addDays(today, 7),
         nextOccurrence: addDays(today, 7),
      },
      {
         userId,
         title: "Insurance Premium",
         amount: 400,
         category: "Insurance",
         startDate: addDays(today, 8),
         nextOccurrence: addDays(today, 8),
      },
   ];
}
