import { addDays, subMonths } from "date-fns";

export function generateIncomes(userId) {
   return [
      {
         userId: userId,
         amount: 500,
         category: "sales revenue",
         date: subMonths(new Date(1), 2),
      },
      {
         userId: userId,
         amount: 300,
         category: "consulting fees",
         date: subMonths(new Date(1), 2),
      },
      {
         userId: userId,
         amount: 700,
         category: "product revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "service revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 400,
         category: "investment income",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "royalties",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "advertising revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 500,
         category: "sales revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 300,
         category: "consulting fees",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 700,
         category: "product revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "service revenue",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 400,
         category: "investment income",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "royalties",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "advertising revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 500,
         category: "sales revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 300,
         category: "consulting fees",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 700,
         category: "product revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2500,
         category: "service revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 400,
         category: "investment income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 600,
         category: "royalties",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3500,
         category: "advertising revenue",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 4500,
         category: "grants",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 5500,
         category: "interest income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 200,
         category: "rental income",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 7500,
         category: "contractual income",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3200,
         category: "subscription revenue",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 4800,
         category: "donations",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3800,
         category: "licensing fees",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 4200,
         category: "sponsorships",
         date: new Date(),
      },
   ];
}

export function generateExpenses(userId) {
   return [
      {
         userId: userId,
         amount: 2500,
         category: "office supplies",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1200,
         category: "marketing",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3500,
         category: "travel expenses",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 800,
         category: "utilities",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1750,
         category: "business meals",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 200,
         category: "equipment",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 900,
         category: "advertising",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 3000,
         category: "insurance",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1500,
         category: "software",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 600,
         category: "training",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 1200,
         category: "consulting",
         date: subMonths(new Date(), 2),
      },
      {
         userId: userId,
         amount: 2500,
         category: "office supplies",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1200,
         category: "marketing",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3500,
         category: "travel expenses",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 800,
         category: "utilities",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1750,
         category: "business meals",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2000,
         category: "equipment",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 900,
         category: "advertising",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 3000,
         category: "insurance",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1500,
         category: "software",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 600,
         category: "training",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 1200,
         category: "consulting",
         date: subMonths(new Date(), 1),
      },
      {
         userId: userId,
         amount: 2500,
         category: "office supplies",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1200,
         category: "marketing",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3500,
         category: "travel expenses",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 800,
         category: "utilities",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1750,
         category: "business meals",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 2000,
         category: "equipment",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 900,
         category: "advertising",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 3000,
         category: "insurance",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1500,
         category: "software",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 600,
         category: "training",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1200,
         category: "consulting",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 1800,
         category: "rent",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 500,
         category: "maintenance",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 700,
         category: "legal fees",
         date: new Date(),
      },
      {
         userId: userId,
         amount: 400,
         category: "transportation",
         date: new Date(),
      },
   ];
}

export function generateRecurringExpenses(userId) {
   const today = new Date();
   return [
      {
         userId,
         title: "Office Supplies",
         amount: 120,
         category: "office expenses",
         startDate: addDays(today, 1),
         nextOccurrence: addDays(today, 1),
      },
      {
         userId,
         title: "Internet Subscription",
         amount: 80,
         category: "utilities",
         startDate: addDays(today, 2),
         nextOccurrence: addDays(today, 2),
      },
      {
         userId,
         title: "Marketing Fees",
         amount: 350,
         category: "marketing",
         startDate: addDays(today, 3),
         nextOccurrence: addDays(today, 3),
      },
      {
         userId,
         title: "Rent",
         amount: 1500,
         category: "office expenses",
         startDate: addDays(today, 4),
         nextOccurrence: addDays(today, 4),
      },
      {
         userId,
         title: "Software Subscription",
         amount: 200,
         category: "software",
         startDate: addDays(today, 5),
         nextOccurrence: addDays(today, 5),
      },
      {
         userId,
         title: "Maintenance Services",
         amount: 300,
         category: "facilities",
         startDate: addDays(today, 6),
         nextOccurrence: addDays(today, 6),
      },
      {
         userId,
         title: "Employee Salaries",
         amount: 5000,
         category: "payroll",
         startDate: addDays(today, 7),
         nextOccurrence: addDays(today, 7),
      },
      {
         userId,
         title: "Insurance Premium",
         amount: 400,
         category: "insurance",
         startDate: addDays(today, 8),
         nextOccurrence: addDays(today, 8),
      },
   ];
}
